Controllers/AdminController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.JsonWebTokens;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NuGet.Common;
using RestaurangWebAPI.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http;
using System.Security.Claims;

namespace RestaurangWebAPI.Controllers
{
    public class AdminController : Controller
    {

        Uri baseAddress = new Uri("https://localhost:7005/api");
        private readonly HttpClient _httpClient;

        public AdminController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }

                public IActionResult Login()
                {
                    return View();
                }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(AdminLogin model)
        {
            if (ModelState.IsValid)
            {

                var response = await _httpClient.PostAsJsonAsync(_httpClient.BaseAddress + "/Admin/Login", model);

                if (response.IsSuccessStatusCode)
                {
                    var jwtToken = await response.Content.ReadAsStringAsync();
                    var token = JsonConvert.DeserializeObject<TokenResponse>(jwtToken);
                    Console.WriteLine(token.Token);

                    var handler = new JwtSecurityTokenHandler();
                    var JwtToken = handler.ReadJwtToken(token.Token);

                    var claims = JwtToken.Claims.ToList();

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, new AuthenticationProperties
                    {
                        IsPersistent = true,
                        ExpiresUtc = JwtToken.ValidTo
                    });

                    HttpContext.Session.SetString("IsAdmin", "true");


                    HttpContext.Response.Cookies.Append("jwtToken", token.Token, new CookieOptions
                    {
                        HttpOnly = true, // Skyddar mot XSS-attacker
                        Secure = true,   // Kräver HTTPS
                        SameSite = SameSiteMode.Strict,
                        Expires = JwtToken.ValidTo
                    });

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    Console.WriteLine(response);
                    ViewBag.Error = "Invalid username or password.";
                }
                
            }

            return View(model);
        }


        public IActionResult Dashboard()
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Login");
            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme); // "Cookies" är autentiseringsschemat om du använder cookies

            // Rensa JWT-token-cookien explicit
            HttpContext.Response.Cookies.Delete("jwtToken");

            HttpContext.Session.Remove("IsAdmin");
            return RedirectToAction("Index", "Home");
        }

    }
}

Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestaurangWebAPI.Models;
using System.Net.Http.Headers;

namespace RestaurangWebAPI.Controllers
{
    public class MenuController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7005/api");
        private readonly HttpClient _httpClient;

        public MenuController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }

        [HttpGet]
        public async  Task<IActionResult> Index()
        {
            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);

            List<MenuViewModel> menuList = new List<MenuViewModel>();
            HttpResponseMessage response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/Menu/GetMenu");

            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                menuList = JsonConvert.DeserializeObject<List<MenuViewModel>>(data);
                return View(menuList);
            }
            else
            {
                // Hantera fel
                ModelState.AddModelError(string.Empty, "An error occurred while fetching menu.");
                return View(new List<MenuViewModel>());
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MenuViewModel model)
        {
            Console.WriteLine(model.FoodName + model.Price + model.IsAvaiable);

            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);
            if (token == null)
            {
                return RedirectToPage("/Login");
            }

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            if (ModelState.IsValid)
            {

                var response = await _httpClient.PostAsJsonAsync(_httpClient.BaseAddress + "/Menu/AddMenu", model);

                if (!response.IsSuccessStatusCode)
                {
                    Console.WriteLine($"API Error: {response.StatusCode}");
                }

                if (response.IsSuccessStatusCode)
                {
                    TempData["Message"] = "Menu added successfully!";
                    return RedirectToAction("Index");
                }
            }

            TempData["Error"] = "Failed to add customer.";
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync(_httpClient.BaseAddress + $"/Menu/{id}");
            if (response.IsSuccessStatusCode)
            {
                var menuItem = await response.Content.ReadFromJsonAsync<MenuViewModel>();
                return View(menuItem);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MenuViewModel model)
        {
            Console.WriteLine(model.FoodName);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);
            if (token == null)
            {
                return RedirectToPage("/Login");
            }

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.PatchAsJsonAsync(_httpClient.BaseAddress + "/Menu/UpdateMenu", model);
            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Menu item updated successfully!";
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to update menu item.";
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.GetAsync(_httpClient.BaseAddress + $"/Menu/{id}");

            if (!response.IsSuccessStatusCode)
            {
                return NotFound();
            }
            var menu = await response.Content.ReadFromJsonAsync<MenuViewModel>();

            return View(menu);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);
            if (token == null)
            {
                return RedirectToPage("/Login");
            }

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.DeleteAsync(_httpClient.BaseAddress + $"/Menu/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestaurangWebAPI.Models;
using System.Net.Http.Headers;

namespace RestaurangWebAPI.Controllers
{
    public class TableController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7005/api");
        private readonly HttpClient _httpClient;

        public TableController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            List<TableViewModel> tableList = new List<TableViewModel>();
            HttpResponseMessage response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/Table/tables/GetAllTables");

            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                tableList = JsonConvert.DeserializeObject<List<TableViewModel>>(data);
                return View(tableList);
            }
            else
            {
                // Hantera fel
                ModelState.AddModelError(string.Empty, "An error occurred while fetching tables.");
                return View(new List<TableViewModel>());
            }
        }

        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(TableViewModel model)
        {
            Console.WriteLine(model.Seats);

            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);
            if (token == null)
            {
                return RedirectToPage("/Login");
            }

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            if (ModelState.IsValid)
            {

                var response = await _httpClient.PostAsJsonAsync(_httpClient.BaseAddress + "/Table/AddTable", model);

                if (!response.IsSuccessStatusCode)
                {
                    Console.WriteLine($"API Error: {response.StatusCode}");
                }

                if (response.IsSuccessStatusCode)
                {
                    TempData["Message"] = "Table added successfully!";
                    return RedirectToAction("Index");
                }
            }

            TempData["Error"] = "Failed to add table.";
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            var response = await _httpClient.GetAsync(_httpClient.BaseAddress + $"/Table/{id}");
            if (response.IsSuccessStatusCode)
            {
                var tableItem = await response.Content.ReadFromJsonAsync<TableViewModel>();
                return View(tableItem);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TableViewModel model)
        {
            Console.WriteLine(model.Seats);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);
            if (token == null)
            {
                return RedirectToPage("/Login");
            }

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.PatchAsJsonAsync(_httpClient.BaseAddress + "/Table/UpdateTable", model);
            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Menu item updated successfully!";
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to update menu item.";
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            var response = await _httpClient.GetAsync(_httpClient.BaseAddress + $"/Table/{id}");

            if (!response.IsSuccessStatusCode)
            {
                return NotFound();
            }
            var table = await response.Content.ReadFromJsonAsync<TableViewModel>();

            return View(table);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var token = Request.Cookies["jwtToken"];
            Console.WriteLine(token);
            if (token == null)
            {
                return RedirectToPage("/Login");
            }

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.DeleteAsync(_httpClient.BaseAddress + $"/Table/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurangWebAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="/css/Home.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestaurangWebAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurangWebAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (HttpContextAccessor.HttpContext.Session.GetString("IsAdmin") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        @if (HttpContextAccessor.HttpContext.Session.GetString("IsAdmin") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Booking</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Create">Booking</a>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetString("IsAdmin") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">Tables</a>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetString("IsAdmin") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RestaurangWebAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>